### ISSUE TITLE
immich-upload-optimizer not compressing images

### ISSUE THREAD

**Issue by SK4G** [miguelangel-nubla/immich-upload-optimizer#10]
When I upload an image the file is the same size as the original. All the immich containers run with no errors in the logs. I copied your personal task.yaml and handbrake.json to ./config

docker-compose.yml
```
name: immich

services:
  immich-upload-optimizer:
    container_name: immich-upload-optimizer
    image: ghcr.io/miguelangel-nubla/immich-upload-optimizer:latest
    ports:
      - "2283:2283"
    volumes:
      - ./config:/etc/immich-upload-optimizer/config
    environment:
      - IUO_UPSTREAM=http://immich-server:2283
      # - IUO_TASKS_FILE=./etc/immich-upload-optimizer/config/tasks.yaml
    depends_on:
      - immich-server
    networks:
      - nginx_proxy

  immich-server:
    container_name: immich
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    # ports:
    #   - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    networks:
      - nginx_proxy

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    networks:
      - nginx_proxy

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - nginx_proxy

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
    networks:
      - nginx_proxy

volumes:
  model-cache:

networks:
  nginx_proxy:
    external: true
```
```
dietpi@DietPi:~/docker-configs/immich-app$ tree
.
├── config
│   ├── handbrake.json
│   └── tasks.yaml
├── docker-compose.yml
├── hwaccel.transcoding.yml
└── postgres
3 directories, 4 files
```

 immich-upload-optimizer logs
```
2025/02/06 02:22:44 Starting immich-upload-optimizer 0.4.7, commit 6a209a4fabd348384cd188ae972043d025b18324, built at 2025-02-04T22:21:11Z on :2283...
```
immich-server logs
```
[Nest] 17  - 02/05/2025, 8:36:50 PM     LOG [Api:RoutesResolver] ViewController {/api/view}:

[Nest] 17  - 02/05/2025, 8:36:50 PM     LOG [Api:RouterExplorer] Mapped {/api/view/folder/unique-paths, GET} route

[Nest] 17  - 02/05/2025, 8:36:50 PM     LOG [Api:RouterExplorer] Mapped {/api/view/folder, GET} route

[Nest] 17  - 02/05/2025, 8:36:50 PM     LOG [Api:NestApplication] Nest application successfully started

[Nest] 17  - 02/05/2025, 8:36:50 PM     LOG [Api:Bootstrap] Immich Server is listening on http://[::1]:2283 [v1.125.7] [production] 
```
