### ISSUE TITLE
Video are not optimized

### ISSUE THREAD

**Issue by mirlipi25** [miguelangel-nubla/immich-upload-optimizer#13]
Hello,
I've installed immich upload optimizer, but my videos and images are not optimized.
The logs : 

> 025/02/09 17:50:52 192.168.1.101: proxy: /api/server/about
> 
> 2025/02/09 17:50:52 192.168.1.101: proxy: /api/server/version-history
> 
> 2025/02/09 17:50:52 192.168.1.101: proxy: /api/timeline/bucket?isArchived=false&size=MONTH&timeBucket=2025-02-01T00%3A00%3A00.000Z&withPartners=true&withStacked=true
> 
> 2025/02/09 17:50:54 192.168.1.101: proxy: /api/assets/da981574-9b1a-4cec-8588-7f2a57c22653/thumbnail?size=thumbnail&c=5O5BNY1jn6Sa8ezCLzcRkCbb1U8%3D
> 
> 2025/02/09 17:50:54 192.168.1.101: proxy: /api/assets/da981574-9b1a-4cec-8588-7f2a57c22653/video/playback?c=5O5BNY1jn6Sa8ezCLzcRkCbb1U8%3D
> 
> 2025/02/09 17:50:54 192.168.1.101: proxy: /api/assets/da981574-9b1a-4cec-8588-7f2a57c22653/video/playback?c=5O5BNY1jn6Sa8ezCLzcRkCbb1U8%3D
> 
> 2025/02/09 17:50:54 192.168.1.101: proxy: /api/assets/da981574-9b1a-4cec-8588-7f2a57c22653/video/playback?c=5O5BNY1jn6Sa8ezCLzcRkCbb1U8%3D
> 
> 2025/02/09 17:50:57 172.18.0.1: proxy: /api/socket.io/?EIO=4&transport=websocket
> 
> 2025/02/09 17:50:58 192.168.1.101: proxy: /api/assets
> 
> 2025/02/09 17:50:59 192.168.1.101: proxy: /api/assets/44b90d2a-4fc3-4dad-b552-e8c22fb0840e/video/playback?c=0SGJJYCNVhIwtpM6eXr0jUqqEkE%3D
> 
> 2025/02/09 17:50:59 192.168.1.101: proxy: /api/assets/44b90d2a-4fc3-4dad-b552-e8c22fb0840e/video/playback?c=0SGJJYCNVhIwtpM6eXr0jUqqEkE%3D
> 
> 2025/02/09 17:50:59 192.168.1.101: proxy: /api/assets/44b90d2a-4fc3-4dad-b552-e8c22fb0840e/video/playback?c=0SGJJYCNVhIwtpM6eXr0jUqqEkE%3D
> 
> 2025/02/09 17:51:00 192.168.1.101: proxy: /_app/immutable/nodes/26.BPSZskZj.js
> 
> 2025/02/09 17:51:02 172.18.0.1: proxy: /api/socket.io/?EIO=4&transport=websocket
> 
> 2025/02/09 17:51:02 192.168.1.101: proxy: /api/timeline/buckets?isTrashed=true&size=MONTH
> 
> 2025/02/09 17:51:02 192.168.1.101: proxy: /api/timeline/bucket?isTrashed=true&size=MONTH&timeBucket=2025-02-01T00%3A00%3A00.000Z
> 
> 2025/02/09 17:51:02 192.168.1.101: proxy: /api/assets/da981574-9b1a-4cec-8588-7f2a57c22653/video/playback?c=5O5BNY1jn6Sa8ezCLzcRkCbb1U8%3D
> 
> 2025/02/09 17:51:07 172.18.0.1: proxy: /api/socket.io/?EIO=4&transport=websocket
> 
> 2025/02/09 17:51:08 192.168.1.101: proxy: /api/assets
> 
> 2025/02/09 17:51:12 172.18.0.1: proxy: /api/socket.io/?EIO=4&transport=websocket
> 
> 2025/02/09 17:51:14 192.168.1.101: proxy: /api/search/explore
> 
> 2025/02/09 17:51:14 192.168.1.101: proxy: /api/people?withHidden=false
> 
> 2025/02/09 17:51:15 192.168.1.101: proxy: /api/assets/memory-lane?day=9&month=2
> 
> 2025/02/09 17:51:15 192.168.1.101: proxy: /api/timeline/buckets?isArchived=false&size=MONTH&withPartners=true&withStacked=true
> 
> 2025/02/09 17:51:16 192.168.1.101: proxy: /api/timeline/bucket?isArchived=false&size=MONTH&timeBucket=2025-02-01T00%3A00%3A00.000Z&withPartners=true&withStacked=true
> 
> 2025/02/09 17:51:17 172.18.0.1: proxy: /api/socket.io/?EIO=4&transport=websocket
> 
> 2025/02/09 17:51:17 192.168.1.101: proxy: /api/server/media-types
> 
> 2025/02/09 17:51:20 192.168.1.101: job ab96186c-16f0-4581-a3ce-d0c769ffb1f6: intercepting upload
> 
> 2025/02/09 17:51:21 192.168.1.101: job ab96186c-16f0-4581-a3ce-d0c769ffb1f6: uploaded VID20250209171122.mp4 54.29 MB
> 
> 2025/02/09 17:51:21 192.168.1.101: job ab96186c-16f0-4581-a3ce-d0c769ffb1f6: running: 
> 
> 2025/02/09 17:51:22 192.168.1.101: job ab96186c-16f0-4581-a3ce-d0c769ffb1f6: file NOT replaced: "VID20250209171122.mp4" 54.29 MB optimized to "VID20250209171122.mp4" 54.29 MB
> 
> 2025/02/09 17:51:22 172.18.0.1: proxy: /api/socket.io/?EIO=4&transport=websocket
> 
> 2025/02/09 17:51:25 192.168.1.101: job ab96186c-16f0-4581-a3ce-d0c769ffb1f6: response sent to client
> 
> 2025/02/09 17:51:27 172.18.0.1: proxy: /api/socket.io/?EIO=4&transport=websocket
> 
> 2025/02/09 17:51:30 192.168.1.101: proxy: /photos
> 
> 2025/02/09 17:51:30 192.168.1.101: proxy: /custom.css
> 
> 2025/02/09 17:51:31 192.168.1.101: proxy: /api/server/config
> 
> 2025/02/09 17:51:31 192.168.1.101: proxy: /api/server/features
> 
> 2025/02/09 17:51:31 192.168.1.101: proxy: /api/users/me
> 
> 2025/02/09 17:51:31 192.168.1.101: proxy: /api/users/me/preferences
> 
> 2025/02/09 17:51:31 192.168.1.101: proxy: /api/server/about
> 
> 2025/02/09 17:51:31 192.168.1.101: proxy: /api/socket.io/?EIO=4&transport=websocket
> 
> 2025/02/09 17:51:31 192.168.1.101: proxy: /api/users/618dc8ba-93af-4c17-9f18-544d3a9e557f/profile-image?updatedAt=2024-11-30T17%3A46%3A30.814Z
> 
> 2025/02/09 17:51:31 192.168.1.101: proxy: /api/albums
> 
> 2025/02/09 17:51:31 192.168.1.101: proxy: /api/server/about
> 
> 2025/02/09 17:51:31 192.168.1.101: proxy: /api/server/storage
> 
> 2025/02/09 17:51:31 192.168.1.101: proxy: /api/assets/memory-lane?day=9&month=2
> 
> 2025/02/09 17:51:31 192.168.1.101: proxy: /api/timeline/buckets?isArchived=false&size=MONTH&withPartners=true&withStacked=true
> 
> 2025/02/09 17:51:31 192.168.1.101: proxy: /api/server/storage
> 
> 2025/02/09 17:51:31 192.168.1.101: proxy: /api/server/version-history
> 
> 2025/02/09 17:51:31 192.168.1.101: proxy: /api/server/about
> 
> 2025/02/09 17:51:31 192.168.1.101: proxy: /api/timeline/bucket?isArchived=false&size=MONTH&timeBucket=2025-02-01T00%3A00%3A00.000Z&withPartners=true&withStacked=true
> 
> 2025/02/09 17:51:32 172.18.0.1: proxy: /api/socket.io/?EIO=4&transport=websocket
> 
> 2025/

02/09 17:51:32 192.168.1.101: proxy: /api/assets/bdd1ecad-8294-430f-b9ee-1f88409e3043/thumbnail?size=thumbnail&c=5O5BNY1jn6Sa8ezCLzcRkCbb1U8%3D
> 
> 2025/02/09 17:51:37 172.18.0.1: proxy: /api/socket.io/?EIO=4&transport=websocket

I have join the handrake.json / tasks.yaml they are located at root/etc/immich-upload-optimizer/config/

[handbrake.json](https://github.com/user-attachments/files/18725759/handbrake.json)
[tasks.yaml.txt](https://github.com/user-attachments/files/18725766/tasks.yaml.txt)
![Image](https://github.com/user-attachments/assets/c285a260-a160-4448-9446-15bb2f1a7707)
thanks for helping

**Comment by mirlipi25** [comment]
Note: the jxl conversion work but the video are not compressed

**Comment by miguelangel-nubla** [comment]
Try `IUO_TASKS_FILE=/etc/immich-upload-optimizer/bundled-configs/profile1/tasks.yaml`

**Comment by mirlipi25** [comment]
Thanks. It's work.
But i want not compress images on jxl, i want only compress vidéo.
When i edit the tasks.yaml and i save the change it doesn't work.
I think i'm not in the good repertory. Where are located the really tasks.yaml?
Thanks for helping

**Comment by miguelangel-nubla** [comment]
If that works you have a problem mounting the files inside the container.

Create a folder in you base os for the config.

Download the files from [here](https://github.com/miguelangel-nubla/immich-upload-optimizer/tree/main/config/profile1) and put them in that config folder.

In the screenshot I don't see a volume mount for the config files. Look at the volumes key:
```
services:
  immich-upload-optimizer:
    image: ghcr.io/miguelangel-nubla/immich-upload-optimizer:latest
    ports:
      - "2283:2283"
    volumes:
      - <full path to config folder in you base os>:/etc/immich-upload-optimizer/config
```

Once you set up a volume mount your config folder in base os will be available at `/etc/immich-upload-optimizer/config` inside the container.

Then remove `IUO_TASKS_FILE` so IUO loads the config from that default location.

It should now work converting photos and videos.

Then modify the `tasks.yaml` file inside your config folder to only do videos:

```
tasks:
  - name: passthrough-images
    command: ""
    extensions:
      # https://immich.app/docs/features/supported-formats/
      - avif
      - bmp
      - gif
      - heic
      - heif
      - webp
      - jpg
      - jpe
      - insp
      - jxl
      - webp
      - psd
      - raw
      - rw2
      - svg
      - tif
      - tiff
      - webp

  - name: handbrake
    command: HandBrakeCLI --preset-import-file handbrake.json -Z immich-upload-optimizer -i {{.folder}}/{{.name}}.{{.extension}} -o {{.folder}}/{{.name}}-new.mkv && rm {{.folder}}/{{.name}}.{{.extension}}
    extensions:
      - 3gp
      - 3gpp
      - avi
      - flv
      - m4v
      - mkv
      - mts
      - m2ts
      - m2t
      - mp4
      - insv
      - mpg
      - mpe
      - mpeg
      - mov
      - webm
      - wmv

  # Block all other formats from being uploaded.
```

and restart the container so it reads the new config.
