### ISSUE TITLE
Issue with Arm 64 image

### ISSUE THREAD

**Issue by NeoHuncho** [miguelangel-nubla/immich-upload-optimizer#16]
Hi, I'm trying to run i**mmich-upload-optimizer on my Raspberry Pi 5 server.** 
However, each time the container runs I **get these logs and then my server crashes**. Would you have any idea why this is happening? 

The logs:
```
2025/02/28 22:21:25 172.25.0.1: proxy: /api/socket.io/?EIO=4&transport=websocket
2025/02/28 22:21:25 172.25.0.1: proxy: /api/socket.io/?EIO=4&transport=websocket
... and the same line many more times
```

My docker-compose file
```
name: immich

services:
  immich-upload-optimizer:
    image: ghcr.io/miguelangel-nubla/immich-upload-optimizer:v0.4.9-arm64v8
    ports:
      - "2283:2283"
    environment:
      IUO_UPSTREAM: ${IMMICH_SERVER_URL}
    # volumes:
    #   - ${OPTIMIZER_TASK_LOCATION}:/etc/immich-upload-optimizer/config
    depends_on:
      - immich-server
# the rest of my immich services ...
```
