### ISSUE TITLE
Should use tmpfs by default on linux

### ISSUE THREAD

**Issue by joojoooo** [miguelangel-nubla/immich-upload-optimizer#22]
The more data you write to an SSD, the sooner it will fail, using immich-upload-optimizer as is will triple your disk writes. Most people don't know they can mount a tmpfs and set the **TMPDIR** environment variable to make immich-upload-optimizer create temporary files in RAM instead of Disk.

I think it should work like that by default with the option to easily disable it if running low on RAM.
Or it should automatically detect available RAM and enable it automatically if more than a certain amount is available.
If anyone wants to try, it's really easy to create a tmpfs:

```
sudo mkdir -p /mnt/my_ramdisk && sudo mount -t tmpfs -o size=1G tmpfs /mnt/my_ramdisk
```
Add volume and TMPDIR environment variable to docker-compose.yml:
```yaml
services:
  immich-upload-optimizer:
    image: ghcr.io/miguelangel-nubla/immich-upload-optimizer:latest
    ports:
      - "2283:2283"
    environment:
      - IUO_UPSTREAM=http://immich-server:2283
      - TMPDIR=/my_ramdisk
    volumes:
      - /mnt/my_ramdisk:/my_ramdisk
    depends_on:
      - immich-server

  immich-server:
  # ...existing configuration...
```
