### ISSUE TITLE
How to configure with traefik

### ISSUE THREAD

**Issue by SK4G** [miguelangel-nubla/immich-upload-optimizer#27]
What traefik configuration is needed to use immich-upload-optimizer with immich?

From the immich docs, adding this to immich or immich-upload-optimizer does not work.
```
   labels:
      traefik.enable: true
      traefik.http.routers.immich.entrypoints: websecure
      traefik.http.routers.immich.rule: Host(`immich.your-domain.com`)
      traefik.http.services.immich.loadbalancer.server.port: 2283
```

Traefik is working to reverse proxy other services.
