### ISSUE TITLE
Image fails to upload when backend shows completed?

### ISSUE THREAD

**Issue by bn-c** [miguelangel-nubla/immich-upload-optimizer#32]
In the docs, timeouts are mentioned. However, is it normal for timeouts to happen in seconds? 
Docker logs shows backend works as normal 

```
immich-upload-optimizer-1  | 2025/06/01 14:48:44 192.168.11.127: job 6ceff8aa-e9e4-4e04-b521-1970435e33ec: intercepting upload
immich-upload-optimizer-1  | 2025/06/01 14:48:44 192.168.11.127: job 6ceff8aa-e9e4-4e04-b521-1970435e33ec: uploaded abc.jpg 2.22 MB
immich-upload-optimizer-1  | 2025/06/01 14:48:44 192.168.11.127: job 6ceff8aa-e9e4-4e04-b521-1970435e33ec: running: ffmpeg -i /tmp/processing-1368320142/file-2838270995.jpg -c:v libaom-av1 -crf 18 -cpu-used 3 -b:v 0 -pix_fmt yuv420p10le -tune ssim -an -y "/tmp/processing-1368320142/file-2838270995-new.avif" -stats && rm /tmp/processing-1368320142/file-2838270995.jpg
immich-upload-optimizer-1  | 2025/06/01 14:48:48 192.168.11.127: job 6ceff8aa-e9e4-4e04-b521-1970435e33ec: file replaced: "abc.jpg" 2.22 MB optimized to "abc.avif" 46.26 KB
immich-upload-optimizer-1  | 2025/06/01 14:48:48 192.168.11.127: job 6ceff8aa-e9e4-4e04-b521-1970435e33ec: response sent to client
immich-upload-optimizer-1  | 2025/06/01 14:48:48 192.168.11.127: proxy: /api/albums/775c4273-7163-47b7-8f02-062348e8a06d/assets
```
![Image](https://github.com/user-attachments/assets/4c031074-df90-4d44-ae0e-114b3cc5e38c)
Below are the task I use
```yaml
      tasks:
        - name: convert-avif
          command: ffmpeg -i {{.folder}}/{{.name}}.{{.extension}} -c:v libaom-av1 -crf 18 -cpu-used 3 -b:v 0 -pix_fmt yuv420p10le -tune ssim -an -y "{{.folder}}/{{.name}}-new.avif" -stats && rm {{.folder}}/{{.name}}.{{.extension}}
          extensions: 
            - bmp
            - heic
            - heif
            - webp
            - jpg
            - jpe
            - insp
            - jxl
            - webp
            - psd
            - raw
            - rw2
            - svg
            - tif
            - tiff
            - webp

        - name: convert-av1
          command: HandBrakeCLI --preset-import-file handbrake.json -Z immich-upload-optimizer -i {{.folder}}/{{.name}}.{{.extension}} -o {{.folder}}/{{.name}}-new.mp4 && rm {{.folder}}/{{.name}}.{{.extension}}
          extensions: 
            - 3gp
            - 3gpp
            - avi
            - flv
            - m4v
            - mkv
            - mts
            - m2ts
            - m2t
            - mp4
            - insv
            - mpg
            - mpe
            - mpeg
            - mov
            - webm
            - wmv
            - gif

        - name: passthrough-images
          command: ""
          extensions:
            - avif
```
