### ISSUE TITLE
Support heic compression

### ISSUE THREAD

**Issue by antomanc** [miguelangel-nubla/immich-upload-optimizer#5]
Is there already a way to compress HEIC files?  All the phones connected to my Immich instance use .heic for images, and being able to compress them would be great.

**Comment by miguelangel-nubla** [comment]
I added `libvips` to the docker image, you can try with:
```
tasks:
  - name: heic2jxl
    command: vips copy {{.folder}}/{{.name}}.{{.extension}} {{.folder}}/{{.name}}-new.jxl[Q=75] && rm {{.folder}}/{{.name}}.{{.extension}}
    extensions:
      - heic
      - heif
```

Note you can play with the `Q=75` quality parameter, 75 is my preference for home use.
